#sdk: "D:/RhoStudio/ruby/lib/ruby/gems/1.8/gems/rhodes-3.3.2"
sdkversion: 3.3.2
name: Rhoiflbeta
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.rhoiflbeta
  BundleURLScheme: rhoiflbeta
wp:
  productid: cd77df30-99ed-0130-73fd-361731d0df79
symbian:
  uid: 3795636082
android:
  version: 2.1
extensions:
  - json
  - another-extension
